carts/urls.py
from django.urls import path

from .views import (
    cart,
    add_cart,
    subtract_cart,
    remove_cart_item,
)

app_name = "ycclav3"

urlpatterns = [
    path('', cart, name="cart"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('subtract_cart/<int:product_id>/', subtract_cart, name="subtract_cart"),
    path('remove_cart_item/<int:product_id>/', remove_cart_item, name="remove_cart_item"),
]

product/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    product_index_view,
)

app_name = "ycclav3"

urlpatterns = [
    path('', product_index_view, name='collections'),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    store,
    product_detail,
)

app_name = "ycclav3"

urlpatterns = [
    path('', store, name='store'),
    path('<slug:category_slug>/', store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ycclav3/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cart/', include('carts.urls', namespace="cart")),
    path('collections/', include('product.urls', namespace="collections")),
    path('store/', include('store.urls', namespace="store")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/footer.html
{% load static %}

<footer class="footerAppear flex space-btwn  footer-styling">
	<a class="nav-button" href="mailto:youcancookliterallyanything@gmail.com"><p>email</p></a>
	<a class="nav-button" href="https://www.instagram.com/youcancookliterallyanything"><p>instagram</p></a>
	<a class="nav-button" href="https://www.tiktok.com/@yccookliterallyanything?_t=8UigZOgkvHy&_r=1"><p>tiktok</p></a>
</footer>

templates/partials/navbar.html
{% load static %}

<nav class="flex space-btwn mobile-column mobile-al-center header-styling"> 
	<h1 class="cream-text">YCCLA</h1>
	<a class="nav-button nav-button-first" href="{% url 'home' %}"><p>About</p></a>
	<a class="nav-button" href="{% url 'collections:collections' %}"><p>Collections</p></a>
	<a class="nav-button" href=""><p>Recipes</p></a>
	<a class="nav-button" href="{% url 'store:store' %}"><p>Store</p></a>
	<a href="{% url 'cart:cart' %}"><p class="cream-text">Cart: {{ cart_count }}</p></a>
</nav>