carts/urls.py
from django.urls import path

from .views import (
    cart,
    add_cart,
    subtract_cart,
    remove_cart_item,
)

app_name = "ycclav3"

urlpatterns = [
    path('', cart, name="cart"),
    path('add_cart/<int:product_id>/', add_cart, name="add_cart"),
    path('subtract_cart/<int:product_id>/', subtract_cart, name="subtract_cart"),
    path('remove_cart_item/<int:product_id>/', remove_cart_item, name="remove_cart_item"),
]

store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from .views import (
    store,
    product_detail,
)

app_name = "ycclav3"

urlpatterns = [
    path('', store, name='store'),
    path('<slug:category_slug>/', store, name='products_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', product_detail, name='product_detail')
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ycclav3/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('cart/', include('carts.urls', namespace="cart")),
    path('collections/', include('product.urls', namespace="collections")),
    path('store/', include('store.urls', namespace="store")),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from email.policy import default
from django.db import models
from product.models import Product, Variation

# Create your models here.

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variations = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.price * self.quantity

    def __unicode__(self):
        return self.product

product/models.py
from django.db import models
from category.models import Category
from django.urls import reverse 

# Create your models here.

class Product(models.Model):

    product_name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    recipe_authors = models.CharField(max_length=100, blank=True)
    illustrators = models.CharField(max_length=100, blank=True)
    price = models.IntegerField()
    images = models.ImageField(upload_to="photos/products")
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    primary_color = models.CharField(max_length=100, default="var(--main-blue)")
    secondary_color = models.CharField(max_length=100, default="var(--main-red)")
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('store:product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

class VariationManager(models.Manager):
    def creatures(self):
        return super(VariationManager, self).filter(variation_category='creature', is_active=True)

    def sizes(self):
        return super(VariationManager, self).filter(variation_category='size', is_active=True)



variation_category_choice = (
    ('creature', 'creature'),
    ('size', 'size')
)

class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_date = models.DateTimeField(auto_now=True)

    objects = VariationManager()

    def __str__(self):
        return self.variation_value

store/models.py
from django.db import models

# Create your models here.

carts/views.py
from math import prod
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from product.models import Product, Variation
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.

def _cart_id(request):

    cart = request.session.session_key
    
    if not cart: 
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id) # get the product
    product_variation = []

    if request.method == 'POST':
        for item in request.POST:
            key = item
            value = request.POST[key]
            print(key, value)

            try: 
                variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                product_variation.append(variation)
                print(variation)
            except:
                pass

    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
        )
    
    cart.save()

    is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
    
    if is_cart_item_exists: 
        cart_item = CartItem.objects.filter(product=product, cart=cart)
        # existing variations -> database
        # current variation -> product_variations
        # item_id -> database
        existing_variation_list = []
        id = []

        for item in cart_item:
            existing_variation = item.variations.all()
            existing_variation_list.append(list(existing_variation))
            id.append(item.id)

        if product_variation in existing_variation_list:
            # increase cart item quantity
            index = existing_variation_list.index(product_variation)
            item_id = id[index]
            item = CartItem.objects.get(product=product, id=item_id)
            item.quantity += 1
            item.save()
        else:
            # create new cart item 
            item = CartItem.objects.create(product=product, quantity=1, cart=cart)
            if len(product_variation) > 0:
                item.variations.clear()
                item.variations.add(*product_variation)
            item.save()

    else: 
        cart_item = CartItem.objects.create(
            product = product,
            quantity = 1,
            cart = cart,
        )
        if len(product_variation) > 0:
            for item in product_variation:
                cart_item.variations.clear()
                cart_item.variations.add(*product_variation)
        cart_item.save()

    return redirect('cart:cart')

def subtract_cart(request, product_id):
    
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else: 
        cart_item.delete()

    return redirect('cart:cart')

def remove_cart_item(request, product_id):
    
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)

    cart_item.delete()

    return redirect('cart:cart')


def cart(request, total=0, quantity=0, cart_items=None):

    try:
        tax = 0
        grand_total = 0
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity
        tax = (8 * total)/100
        grand_total = total + tax
    except ObjectDoesNotExist:
        pass

    context = {
        'total' : total,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax' : tax,
        'grand_total' : grand_total,
    }    

    return render(request, 'cart.html', context)

store/views.py
from tkinter import E
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from product.models import Product
from category.models import Category
from carts.views import _cart_id
from carts.models import CartItem

# Create your views here.

def store(request, category_slug=None):        
    categories = None
    products = None

    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        product_count = products.count()
    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        product_count = products.count()

    context = {
        'products' : products,
    }

    return render(request, 'store.html', context)

def product_detail(request, category_slug, product_slug):
    
    try: 
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()
    except Exception as e:
        raise E
    
    context = {
        'single_product': single_product,
        'in_cart' : in_cart,
    }

    return render(request, 'product_detail.html', context)

store/templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <div class="inlay-padding clay-border-three double-border-three bg-blue">
        <div class="flex column al-center clay-border-three">
            <div class="fifty-vw margin-bottom bg-cream clay-border-three">
                <div class="flex column al-center padding">
                    <div class="margin-top">
                        <table>
                            {% if not cart_items %}
                                <h2>Your cart is empty.</h2>
                                <a href="{% url 'store:store' %}">Continue shopping</a>
                            {% else %}
                                <h2>Cart</h2>
                                {% for cart_item in cart_items %}
                                    <tr>
                                        <td>
                                            <img src="{{ cart_item.product.images.url }}" class="image-width image-height">
                                        </td>
                                        <div>
                                            <a href="{{ cart_item.product.get_url }}">{{ cart_item.product.product_name }}</a>
                                            <p>
                                                {% if cart_item.variations.all %}
                                                    {% for item in cart_item.variations.all %}
                                                        {{ item.variation_category }} : {{ item.variation_value }}
                                                    {% endfor %}
                                                {% endif %}
                                            </p>
                                            <a href="{% url 'cart:subtract_cart' cart_item.product.id %}">-</a>
                                            <input type="text" value="{{ cart_item.quantity }}">
                                            <a href="{% url 'cart:add_cart' cart_item.product.id %}">+</a>
                                            <p>$ {{ cart_item.product.price }} each</p>
                                            <p>$ {{ cart_item.sub_total }}</p>
                                            <a href="{% url 'cart:remove_cart_item' cart_item.product.id %}">Remove</a>
                                        </div>
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        </table>
                        <h2>$ {{ total }}</h2>
                        <h2>$ {{ tax }}</h2>
                        <h2>$ {{ grand_total }}</h2>
                    </div>
                </div>
            </div>
        </div>        
    </div>
{% endblock body %}

store/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    {% include 'partials/storesubnav.html' %}
    <div class="openDrawer inlay-padding clay-border-three double-border-three bg-blue">
        <div class="flex column al-center clay-border-three">
            <div class="fifty-vw margin-bottom bg-cream clay-border-three">
                <div class="flex column al-center padding">
                    <div class="margin-top">
                        <img class="image-width image-height"src="{{ single_product.images.url }}" />
                        <div class="flex column padding">
                            <form action="{% url 'cart:add_cart' single_product.id %}" method="POST">
                                {% csrf_token %}
                                <div>
                                    <div class="flex space-btwn">
                                        <h2 class="HWT no-margin" style="color: {{ single_product.primary_color }}">{{ single_product.product_name }}</h2>
                                        <h2 class="HWT no-margin" style="color: {{ single_product.primary_color }}">${{ single_product.price }}</h2>
                                    </div>
                                    <p class="no-margin" style="color: {{ single_product.primary_color }}">Recipes by: {{ single_product.recipe_authors }}</p>
                                    <p class="no-margin" style="color: {{ single_product.primary_color }}">Illustrations by: {{ single_product.illustrators}}</p>
                                </div>
                                <p style="color: {{ single_product.secondary_color }}">{{ single_product.description }}</p>
                                {% if single_product.variation_set.count > 0 %}
                                    <p class="no-margin" style="color: {{ single_product.secondary_color }}" >{{ single_product.variation_set.creatures.0.variation_category | capfirst }}</p>
                                    <select name="creature" required>
                                        <option value="" disabled selected>Choose YCCLA Pin</option>
                                        {% for i in single_product.variation_set.creatures %}
                                            <option value="{{ i.variation_value }}">{{ i.variation_value }}</option>
                                        {% endfor %}    
                                    </select>
                                {% endif %}    
                                <div class="flex jc-center">
                                    {% if single_product.stock <= 0 %}
                                        <h4 class="out-of-stock" style="color: {{ single_product.secondary_color }}; background-color: {{ single_product.primary_color }}">Out of stock</h4>
                                    {% else %}
                                        {% if in_cart %}
                                            <button type="submit" class="checkout-button" style="color: {{ single_product.secondary_color }}; border-color: {{ single_product.secondary_color }}; background-color: {{ single_product.primary_color }};"><h4 class="HWT">Add to cart</h4></button>
                                            <p style="color: {{ single_product.primary_color }}" class="HWT">Added to cart</p>
                                            <a href="{% url 'cart:cart' %}" class="checkout-button" style="color: {{ single_product.secondary_color }}; border-color: {{ single_product.secondary_color }}; background-color: {{ single_product.primary_color }};"><h4 class="HWT">View cart</h4></a>
                                        {% else %}
                                            <button type="submit" class="checkout-button" style="color: {{ single_product.secondary_color }}; border-color: {{ single_product.secondary_color }}; background-color: {{ single_product.primary_color }};"><h4 class="HWT">Add to cart</h4></button>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>        
    </div>
{% endblock body %}

store/templates/store.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
    {% include 'partials/storesubnav.html' %}
    <div class="openDrawer inlay-padding clay-border-three double-border-three bg-blue">
        <div class="flex column al-center clay-border-three">
            <div class="fifty-vw margin-bottom bg-cream clay-border-three">
                <div class="flex column al-center padding">
                    {% for product in products %}
                        <div class="margin-top">
                            <img class="image-width image-height"src="{{ product.images.url }}" />
                            <div class="flex column padding">
                                <div >
                                    <div class="flex space-btwn">
                                        <a href="{{ product.get_url }}"><h2 class="HWT no-margin" style="color: {{ product.primary_color }}">{{ product.product_name }}</h2></a>
                                        <h2 class="HWT no-margin" style="color: {{ product.primary_color }}">${{ product.price }}</h2>
                                    </div>
                                    <p class="no-margin" style="color: {{ product.primary_color }}">Recipes by: {{ product.recipe_authors }}</p>
                                    <p class="no-margin" style="color: {{ product.primary_color }}">Illustrations by: {{ product.illustrators}}</p>
                                </div>
                                <p style="color: {{ product.secondary_color }}">{{ product.description }}</p>
                                <div class="flex jc-center">
                                    {% if product.stock <= 0 %}
                                        <h4 class="out-of-stock" style="color: {{ product.secondary_color }}; background-color: {{ product.primary_color }}">Out of stock</h4>
                                    {% else %}
                                        
                                        <a href="{% url 'cart:add_cart' product.id %}" class="checkout-button" style="color: {{ product.secondary_color }}; border-color: {{ product.secondary_color }}; background-color: {{ product.primary_color }};"><h4 class="HWT">Add to cart</h4></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>        
    </div>
{% endblock body %}